name: COVID-19 Data Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: covid19
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run dbt models
      env:
        DBT_PROFILES_DIR: /tmp  # Temporarily set profiles directory to a dummy path
        DBT_PROFILE: "covid19_profile"
        DBT_TARGET: "dev"
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: "localhost"
        DB_PORT: "5432"
        DB_NAME: "covid19"
      run: |
        dbt run --profiles-dir /tmp --profile covid19_profile --target dev

    - name: Run dbt tests
      env:
        DBT_PROFILES_DIR: /tmp
        DBT_PROFILE: "covid19_profile"
        DBT_TARGET: "dev"
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: "localhost"
        DB_PORT: "5432"
        DB_NAME: "covid19"
      run: |
        dbt test --profiles-dir /tmp --profile covid19_profile --target dev
